# Configuration SIA (CLI)

[env]  # variables d'environnement spécifiques à ce run (optionnel)
# LLM_MODE = "api"            # ou "local"
# OPENAI_API_KEY = "..."      # requis en mode api
# VLLM_BASE_URL = "http://127.0.0.1:8001/v1"  # requis en mode local
CLI_WORKERS = "12"
API_WORKERS = "1"
CONSOLIDATION_BATCH_SIZE = "250"
CONSOLIDATION_ROUNDS = "4"
MAX_CATEGORIES = "20"
MERGE_THRESHOLD = "0.86"

[run]
profile = "default"

[profiles.default]
input = "data/tickets_jira.csv"
output = "outputs/out.csv"
format = "csv"
consolidate = true
save_intermediate = "outputs/stage.jsonl"
consolidation_batch_size = 250
consolidation_rounds = 4
workers = 12
limit = 0

[profiles.resume]
resume_consolidate_from = "outputs/stage.jsonl"
output = "outputs/final.csv"
format = "csv"
consolidation_batch_size = 250
consolidation_rounds = 4
